// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrashInfo.proto

public final class CrashInfo {
  private CrashInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
