// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.compass.ux.netty_lib.zhang;

import com.compass.ux.netty_lib.zhang.Communication;

public final class ProtoMessage {
    private ProtoMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string requestId = 1;</code>
         *
         * @return The requestId.
         */
        String getRequestId();

        /**
         * <code>string requestId = 1;</code>
         *
         * @return The bytes for requestId.
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>string equipmentId = 2;</code>
         *
         * @return The equipmentId.
         */
        String getEquipmentId();

        /**
         * <code>string equipmentId = 2;</code>
         *
         * @return The bytes for equipmentId.
         */
        com.google.protobuf.ByteString
        getEquipmentIdBytes();

        /**
         * <code>string method = 3;</code>
         *
         * @return The method.
         */
        String getMethod();

        /**
         * <code>string method = 3;</code>
         *
         * @return The bytes for method.
         */
        com.google.protobuf.ByteString
        getMethodBytes();

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        int getParaCount();

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        boolean containsPara(
                String key);

        /**
         * Use {@link #getParaMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getPara();

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        java.util.Map<String, String>
        getParaMap();

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */

        String getParaOrDefault(
                String key,
                String defaultValue);

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */

        String getParaOrThrow(
                String key);

        /**
         * <code>sint32 code = 5;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <code>string result = 6;</code>
         *
         * @return The result.
         */
        String getResult();

        /**
         * <code>string result = 6;</code>
         *
         * @return The bytes for result.
         */
        com.google.protobuf.ByteString
        getResultBytes();

        /**
         * <code>string requestTime = 7;</code>
         *
         * @return The requestTime.
         */
        String getRequestTime();

        /**
         * <code>string requestTime = 7;</code>
         *
         * @return The bytes for requestTime.
         */
        com.google.protobuf.ByteString
        getRequestTimeBytes();

        /**
         * <code>string responseTime = 8;</code>
         *
         * @return The responseTime.
         */
        String getResponseTime();

        /**
         * <code>string responseTime = 8;</code>
         *
         * @return The bytes for responseTime.
         */
        com.google.protobuf.ByteString
        getResponseTimeBytes();
    }

    /**
     * <pre>
     * 这里是注释juanq
     * </pre>
     * <p>
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            requestId_ = "";
            equipmentId_ = "";
            method_ = "";
            result_ = "";
            requestTime_ = "";
            responseTime_ = "";
        }

        public Communication CoverCommunication() {
            return CommunicationBuilder
                    .aCommunication()
                    .withEquipmentId(getEquipmentId())
                    .withMethod(getMethod())
                    .withResult(getResult())
                    .withPara(getParaMap())
                    .withCode(getCode())
                    .withRequestId(getRequestId())
                    .withRequestTime(getRequestTime())
                    .withResponseTime(getResponseTime())
                    .build();
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new Message();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                return;
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            requestId_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            equipmentId_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            method_ = s;
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                para_ = com.google.protobuf.MapField.newMapField(
                                        ParaDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    para__ = input.readMessage(
                                    ParaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            para_.getMutableMap().put(
                                    para__.getKey(), para__.getValue());
                            break;
                        }
                        case 40: {

                            code_ = input.readSInt32();
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            result_ = s;
                            break;
                        }
                        case 58: {
                            String s = input.readStringRequireUtf8();

                            requestTime_ = s;
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            responseTime_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoMessage.internal_static_Message_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetPara();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoMessage.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProtoMessage.Message.class, ProtoMessage.Message.Builder.class);
        }

        public static final int REQUESTID_FIELD_NUMBER = 1;
        private volatile Object requestId_;

        /**
         * <code>string requestId = 1;</code>
         *
         * @return The requestId.
         */
        @Override
        public String getRequestId() {
            Object ref = requestId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestId_ = s;
                return s;
            }
        }

        /**
         * <code>string requestId = 1;</code>
         *
         * @return The bytes for requestId.
         */
        @Override
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            Object ref = requestId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EQUIPMENTID_FIELD_NUMBER = 2;
        private volatile Object equipmentId_;

        /**
         * <code>string equipmentId = 2;</code>
         *
         * @return The equipmentId.
         */
        @Override
        public String getEquipmentId() {
            Object ref = equipmentId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                equipmentId_ = s;
                return s;
            }
        }

        /**
         * <code>string equipmentId = 2;</code>
         *
         * @return The bytes for equipmentId.
         */
        @Override
        public com.google.protobuf.ByteString
        getEquipmentIdBytes() {
            Object ref = equipmentId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                equipmentId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_FIELD_NUMBER = 3;
        private volatile Object method_;

        /**
         * <code>string method = 3;</code>
         *
         * @return The method.
         */
        @Override
        public String getMethod() {
            Object ref = method_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                method_ = s;
                return s;
            }
        }

        /**
         * <code>string method = 3;</code>
         *
         * @return The bytes for method.
         */
        @Override
        public com.google.protobuf.ByteString
        getMethodBytes() {
            Object ref = method_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PARA_FIELD_NUMBER = 4;

        private static final class ParaDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    ProtoMessage.internal_static_Message_ParaEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                String, String> para_;

        private com.google.protobuf.MapField<String, String>
        internalGetPara() {
            if (para_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        ParaDefaultEntryHolder.defaultEntry);
            }
            return para_;
        }

        public int getParaCount() {
            return internalGetPara().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */

        @Override
        public boolean containsPara(
                String key) {
            if (key == null) {
                return false;
            }
            return internalGetPara().getMap().containsKey(key);
        }

        /**
         * Use {@link #getParaMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, String> getPara() {
            return getParaMap();
        }

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        @Override

        public java.util.Map<String, String> getParaMap() {
            return internalGetPara().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        @Override

        public String getParaOrDefault(
                String key,
                String defaultValue) {
            if (key == null) {
                return null;
            }
            java.util.Map<String, String> map =
                    internalGetPara().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; para = 4;</code>
         */
        @Override

        public String getParaOrThrow(
                String key) {
            if (key == null) {
                return null;
            }
            java.util.Map<String, String> map =
                    internalGetPara().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int CODE_FIELD_NUMBER = 5;
        private int code_;

        /**
         * <code>sint32 code = 5;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        public static final int RESULT_FIELD_NUMBER = 6;
        private volatile Object result_;

        /**
         * <code>string result = 6;</code>
         *
         * @return The result.
         */
        @Override
        public String getResult() {
            Object ref = result_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                result_ = s;
                return s;
            }
        }

        /**
         * <code>string result = 6;</code>
         *
         * @return The bytes for result.
         */
        @Override
        public com.google.protobuf.ByteString
        getResultBytes() {
            Object ref = result_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                result_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REQUESTTIME_FIELD_NUMBER = 7;
        private volatile Object requestTime_;

        /**
         * <code>string requestTime = 7;</code>
         *
         * @return The requestTime.
         */
        @Override
        public String getRequestTime() {
            Object ref = requestTime_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestTime_ = s;
                return s;
            }
        }

        /**
         * <code>string requestTime = 7;</code>
         *
         * @return The bytes for requestTime.
         */
        @Override
        public com.google.protobuf.ByteString
        getRequestTimeBytes() {
            Object ref = requestTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RESPONSETIME_FIELD_NUMBER = 8;
        private volatile Object responseTime_;

        /**
         * <code>string responseTime = 8;</code>
         *
         * @return The responseTime.
         */
        @Override
        public String getResponseTime() {
            Object ref = responseTime_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                responseTime_ = s;
                return s;
            }
        }

        /**
         * <code>string responseTime = 8;</code>
         *
         * @return The bytes for responseTime.
         */
        @Override
        public com.google.protobuf.ByteString
        getResponseTimeBytes() {
            Object ref = responseTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                responseTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRequestIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
            }
            if (!getEquipmentIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, equipmentId_);
            }
            if (!getMethodBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetPara(),
                            ParaDefaultEntryHolder.defaultEntry,
                            4);
            if (code_ != 0) {
                output.writeSInt32(5, code_);
            }
            if (!getResultBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, result_);
            }
            if (!getRequestTimeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, requestTime_);
            }
            if (!getResponseTimeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, responseTime_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRequestIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
            }
            if (!getEquipmentIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, equipmentId_);
            }
            if (!getMethodBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
            }
            for (java.util.Map.Entry<String, String> entry
                    : internalGetPara().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        para__ = ParaDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, para__);
            }
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(5, code_);
            }
            if (!getResultBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, result_);
            }
            if (!getRequestTimeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, requestTime_);
            }
            if (!getResponseTimeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, responseTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ProtoMessage.Message)) {
                return super.equals(obj);
            }
            ProtoMessage.Message other = (ProtoMessage.Message) obj;

            if (!getRequestId()
                    .equals(other.getRequestId())) return false;
            if (!getEquipmentId()
                    .equals(other.getEquipmentId())) return false;
            if (!getMethod()
                    .equals(other.getMethod())) return false;
            if (!internalGetPara().equals(
                    other.internalGetPara())) return false;
            if (getCode()
                    != other.getCode()) return false;
            if (!getResult()
                    .equals(other.getResult())) return false;
            if (!getRequestTime()
                    .equals(other.getRequestTime())) return false;
            if (!getResponseTime()
                    .equals(other.getResponseTime())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId().hashCode();
            hash = (37 * hash) + EQUIPMENTID_FIELD_NUMBER;
            hash = (53 * hash) + getEquipmentId().hashCode();
            hash = (37 * hash) + METHOD_FIELD_NUMBER;
            hash = (53 * hash) + getMethod().hashCode();
            if (!internalGetPara().getMap().isEmpty()) {
                hash = (37 * hash) + PARA_FIELD_NUMBER;
                hash = (53 * hash) + internalGetPara().hashCode();
            }
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + getResult().hashCode();
            hash = (37 * hash) + REQUESTTIME_FIELD_NUMBER;
            hash = (53 * hash) + getRequestTime().hashCode();
            hash = (37 * hash) + RESPONSETIME_FIELD_NUMBER;
            hash = (53 * hash) + getResponseTime().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ProtoMessage.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoMessage.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoMessage.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoMessage.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoMessage.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoMessage.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoMessage.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoMessage.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoMessage.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ProtoMessage.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoMessage.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoMessage.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ProtoMessage.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 这里是注释juanq
         * </pre>
         * <p>
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                ProtoMessage.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoMessage.internal_static_Message_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetPara();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutablePara();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoMessage.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ProtoMessage.Message.class, ProtoMessage.Message.Builder.class);
            }

            // Construct using ProtoMessage.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                requestId_ = "";

                equipmentId_ = "";

                method_ = "";

                internalGetMutablePara().clear();
                code_ = 0;

                result_ = "";

                requestTime_ = "";

                responseTime_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoMessage.internal_static_Message_descriptor;
            }

            @Override
            public ProtoMessage.Message getDefaultInstanceForType() {
                return ProtoMessage.Message.getDefaultInstance();
            }

            @Override
            public ProtoMessage.Message build() {
                ProtoMessage.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ProtoMessage.Message buildPartial() {
                ProtoMessage.Message result = new ProtoMessage.Message(this);
                int from_bitField0_ = bitField0_;
                result.requestId_ = requestId_;
                result.equipmentId_ = equipmentId_;
                result.method_ = method_;
                result.para_ = internalGetPara();
                result.para_.makeImmutable();
                result.code_ = code_;
                result.result_ = result_;
                result.requestTime_ = requestTime_;
                result.responseTime_ = responseTime_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ProtoMessage.Message) {
                    return mergeFrom((ProtoMessage.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ProtoMessage.Message other) {
                if (other == ProtoMessage.Message.getDefaultInstance())
                    return this;
                if (!other.getRequestId().isEmpty()) {
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (!other.getEquipmentId().isEmpty()) {
                    equipmentId_ = other.equipmentId_;
                    onChanged();
                }
                if (!other.getMethod().isEmpty()) {
                    method_ = other.method_;
                    onChanged();
                }
                internalGetMutablePara().mergeFrom(
                        other.internalGetPara());
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getResult().isEmpty()) {
                    result_ = other.result_;
                    onChanged();
                }
                if (!other.getRequestTime().isEmpty()) {
                    requestTime_ = other.requestTime_;
                    onChanged();
                }
                if (!other.getResponseTime().isEmpty()) {
                    responseTime_ = other.responseTime_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ProtoMessage.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ProtoMessage.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object requestId_ = "";

            /**
             * <code>string requestId = 1;</code>
             *
             * @return The requestId.
             */
            public String getRequestId() {
                Object ref = requestId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    requestId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string requestId = 1;</code>
             *
             * @return The bytes for requestId.
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string requestId = 1;</code>
             *
             * @param value The requestId to set.
             * @return This builder for chaining.
             */
            public Builder setRequestId(
                    String value) {
                if (value == null) {
                    return this;
                }

                requestId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string requestId = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRequestId() {

                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }

            /**
             * <code>string requestId = 1;</code>
             *
             * @param value The bytes for requestId to set.
             * @return This builder for chaining.
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                requestId_ = value;
                onChanged();
                return this;
            }

            private Object equipmentId_ = "";

            /**
             * <code>string equipmentId = 2;</code>
             *
             * @return The equipmentId.
             */
            public String getEquipmentId() {
                Object ref = equipmentId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    equipmentId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string equipmentId = 2;</code>
             *
             * @return The bytes for equipmentId.
             */
            public com.google.protobuf.ByteString
            getEquipmentIdBytes() {
                Object ref = equipmentId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    equipmentId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string equipmentId = 2;</code>
             *
             * @param value The equipmentId to set.
             * @return This builder for chaining.
             */
            public Builder setEquipmentId(
                    String value) {
                if (value == null) {
                    return this;
                }

                equipmentId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string equipmentId = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEquipmentId() {

                equipmentId_ = getDefaultInstance().getEquipmentId();
                onChanged();
                return this;
            }

            /**
             * <code>string equipmentId = 2;</code>
             *
             * @param value The bytes for equipmentId to set.
             * @return This builder for chaining.
             */
            public Builder setEquipmentIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                equipmentId_ = value;
                onChanged();
                return this;
            }

            private Object method_ = "";

            /**
             * <code>string method = 3;</code>
             *
             * @return The method.
             */
            public String getMethod() {
                Object ref = method_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string method = 3;</code>
             *
             * @return The bytes for method.
             */
            public com.google.protobuf.ByteString
            getMethodBytes() {
                Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string method = 3;</code>
             *
             * @param value The method to set.
             * @return This builder for chaining.
             */
            public Builder setMethod(
                    String value) {
                if (value == null) {
                    return this;
                }

                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string method = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMethod() {

                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>string method = 3;</code>
             *
             * @param value The bytes for method to set.
             * @return This builder for chaining.
             */
            public Builder setMethodBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                method_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, String> para_;

            private com.google.protobuf.MapField<String, String>
            internalGetPara() {
                if (para_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            ParaDefaultEntryHolder.defaultEntry);
                }
                return para_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMutablePara() {
                onChanged();
                ;
                if (para_ == null) {
                    para_ = com.google.protobuf.MapField.newMapField(
                            ParaDefaultEntryHolder.defaultEntry);
                }
                if (!para_.isMutable()) {
                    para_ = para_.copy();
                }
                return para_;
            }

            public int getParaCount() {
                return internalGetPara().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */

            @Override
            public boolean containsPara(
                    String key) {
                if (key == null) {
                    return false;
                }
                return internalGetPara().getMap().containsKey(key);
            }

            /**
             * Use {@link #getParaMap()} instead.
             */
            @Override
            @Deprecated
            public java.util.Map<String, String> getPara() {
                return getParaMap();
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */
            @Override

            public java.util.Map<String, String> getParaMap() {
                return internalGetPara().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */
            @Override

            public String getParaOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) {
                    return null;
                }
                java.util.Map<String, String> map =
                        internalGetPara().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */
            @Override

            public String getParaOrThrow(
                    String key) {
                if (key == null) {
                    return null;
                }
                java.util.Map<String, String> map =
                        internalGetPara().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearPara() {
                internalGetMutablePara().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */

            public Builder removePara(
                    String key) {
                if (key == null) {
                    return this;
                }
                internalGetMutablePara().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutablePara() {
                return internalGetMutablePara().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */
            public Builder putPara(
                    String key,
                    String value) {
                if (key == null) {
                    return this;
                }
                if (value == null) {
                    return this;
                }
                internalGetMutablePara().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; para = 4;</code>
             */

            public Builder putAllPara(
                    java.util.Map<String, String> values) {
                if (values == null || values.size() == 0) {
                    return this;
                }

                internalGetMutablePara().getMutableMap()
                        .putAll(values);
                return this;
            }

            private int code_;

            /**
             * <code>sint32 code = 5;</code>
             *
             * @return The code.
             */
            @Override
            public int getCode() {
                return code_;
            }

            /**
             * <code>sint32 code = 5;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>sint32 code = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {

                code_ = 0;
                onChanged();
                return this;
            }

            private Object result_ = "";

            /**
             * <code>string result = 6;</code>
             *
             * @return The result.
             */
            public String getResult() {
                Object ref = result_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    result_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string result = 6;</code>
             *
             * @return The bytes for result.
             */
            public com.google.protobuf.ByteString
            getResultBytes() {
                Object ref = result_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    result_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string result = 6;</code>
             *
             * @param value The result to set.
             * @return This builder for chaining.
             */
            public Builder setResult(
                    String value) {
                if (value == null) {
                    return this;
                }

                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string result = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResult() {

                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            /**
             * <code>string result = 6;</code>
             *
             * @param value The bytes for result to set.
             * @return This builder for chaining.
             */
            public Builder setResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                result_ = value;
                onChanged();
                return this;
            }

            private Object requestTime_ = "";

            /**
             * <code>string requestTime = 7;</code>
             *
             * @return The requestTime.
             */
            public String getRequestTime() {
                Object ref = requestTime_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    requestTime_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string requestTime = 7;</code>
             *
             * @return The bytes for requestTime.
             */
            public com.google.protobuf.ByteString
            getRequestTimeBytes() {
                Object ref = requestTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    requestTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string requestTime = 7;</code>
             *
             * @param value The requestTime to set.
             * @return This builder for chaining.
             */
            public Builder setRequestTime(
                    String value) {
                if (value == null) {
                    return this;
                }

                requestTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string requestTime = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRequestTime() {

                requestTime_ = getDefaultInstance().getRequestTime();
                onChanged();
                return this;
            }

            /**
             * <code>string requestTime = 7;</code>
             *
             * @param value The bytes for requestTime to set.
             * @return This builder for chaining.
             */
            public Builder setRequestTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                requestTime_ = value;
                onChanged();
                return this;
            }

            private Object responseTime_ = "";

            /**
             * <code>string responseTime = 8;</code>
             *
             * @return The responseTime.
             */
            public String getResponseTime() {
                Object ref = responseTime_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    responseTime_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string responseTime = 8;</code>
             *
             * @return The bytes for responseTime.
             */
            public com.google.protobuf.ByteString
            getResponseTimeBytes() {
                Object ref = responseTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    responseTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string responseTime = 8;</code>
             *
             * @param value The responseTime to set.
             * @return This builder for chaining.
             */
            public Builder setResponseTime(
                    String value) {
                if (value == null) {
                    return this;
                }

                responseTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string responseTime = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResponseTime() {

                responseTime_ = getDefaultInstance().getResponseTime();
                onChanged();
                return this;
            }

            /**
             * <code>string responseTime = 8;</code>
             *
             * @param value The bytes for responseTime to set.
             * @return This builder for chaining.
             */
            public Builder setResponseTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    return this;
                }
                checkByteStringIsUtf8(value);

                responseTime_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final ProtoMessage.Message DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ProtoMessage.Message();
        }

        public static ProtoMessage.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @Override
        public ProtoMessage.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_ParaEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_ParaEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022ProtoMessage.proto\"\331\001\n\007Message\022\021\n\trequ" +
                        "estId\030\001 \001(\t\022\023\n\013equipmentId\030\002 \001(\t\022\016\n\006meth" +
                        "od\030\003 \001(\t\022 \n\004para\030\004 \003(\0132\022.Message.ParaEnt" +
                        "ry\022\014\n\004code\030\005 \001(\021\022\016\n\006result\030\006 \001(\t\022\023\n\013requ" +
                        "estTime\030\007 \001(\t\022\024\n\014responseTime\030\010 \001(\t\032+\n\tP" +
                        "araEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
                        "B$\n\024com.luopan.uav.modelB\014ProtoMessageb\006" +
                        "proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new String[]{"RequestId", "EquipmentId", "Method", "Para", "Code", "Result", "RequestTime", "ResponseTime",});
        internal_static_Message_ParaEntry_descriptor =
                internal_static_Message_descriptor.getNestedTypes().get(0);
        internal_static_Message_ParaEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_ParaEntry_descriptor,
                new String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
